dataset: MOST
model: joint_unet
data_root: E:\MOST
output_dir: C:\Users\James\Documents\projects\KneeOA\Training\2nd_run
inference_dir: C:\Users\James\Documents\projects\KneeOA\Training\2nd_run\inference
overwrite_data: false
resize:
  height: 240
  width: 288
save_name: joint_segmentation
epochs: 100
backend: tensorflow
preprocessing: clahe
optimizer: nadam