dataset: MOST
model: joint_unet
data_root: /home/mdp/data/MOST
output_dir: /home/mdp/data/Training
overwrite_data: false
resize:
  height: 480
  width: 576
save_name: joint_segmentation
epochs: 100
backend: tensorflow
