dataset: MOST
model: joint_unet
data_root: /root/data/MOST
output_dir: /root/data/Training
overwrite_data: false
resize:
  height: 240
  width: 288
save_name: joint_segmentation
epochs: 100
backend: tensorflow
